# Generated by Django 4.2.16 on 2026-01-13 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, verbose_name='ABC\\DEF')),
                ('startRange', models.BigIntegerField(verbose_name='От')),
                ('endRange', models.BigIntegerField(verbose_name='До')),
                ('capacity', models.IntegerField(verbose_name='Емкость')),
                ('operator', models.CharField(max_length=255, verbose_name='Оператор')),
                ('region', models.CharField(max_length=255, verbose_name='Регион')),
                ('inn', models.CharField(max_length=20, verbose_name='Инн')),
                ('dateUpdate', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'indexes': [models.Index(fields=['startRange', 'endRange'], name='check_phone_startRa_9b0cb4_idx'), models.Index(fields=['operator'], name='check_phone_operato_108b1b_idx')],
            },
        ),
    ]
