# Generated by Django 4.2.16 on 2026-01-14 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_phone_api', '0002_alter_phonerange_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonerange',
            name='code',
            field=models.CharField(max_length=40, verbose_name='ABC\\DEF'),
        ),
    ]
